dev:
  sessions:
    default:
      identity_map_enabled: true
      database: autohome
      hosts:
        - 192.168.2.14:27017
local:
  sessions:
    default:
      identity_map_enabled: true
      database: automotive
      hosts:
        - 127.0.0.1:27017
saidan:
  sessions:
    default:
      identity_map_enabled: true
      database: autohomesaidan
      hosts:
        - 127.0.0.1:27017
test:
  sessions:
    default:
      identity_map_enabled: true
      database: test
      hosts:
        - 127.0.0.1:27017

