dev:
  sessions:
    default:
      identity_map_enabled: true
      database: autohome
      hosts:
        - 192.168.2.14:27017
local:
  sessions:
    default:
      identity_map_enabled: true
      database: automotive
      hosts:
        - 127.0.0.1:27017
test:
  sessions:
    default:
      identity_map_enabled: true
      database: test
      hosts:
        - 127.0.0.1:27017
dataserver:
  sessions:
    default:
      identity_map_enabled: true
      database: automotive
      hosts:
        - 192.168.1.2:27017
dataserver2:
  sessions:
    default:
      identity_map_enabled: true
      database: automotive
      hosts:
        - 192.168.2.24:27017

chezhongguo:
  sessions:
    default:
      identity_map_enabled: true	
      database: chezhongguo
      hosts:
        - www.baigoosoft.com:27017

